admins:
  - a@test.com

users:
  - b@test.com

groups:
  - name: AWS Developers
    id: developers
    members:
      - a@test.com
      - b@test.com
roles:
  - id: admin
    type: ROLE_TYPE_AWS
    audited: true
    accounts:
      - acct: 123456789012
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
          }
        ]
      }
    sessionDuration: 2h
