// Code generated by "enumer -type=Status -linecomment"; DO NOT EDIT.

//
package gconfig

import (
	"fmt"
)

const _StatusName = "PENDINGAPPROVED"

var _StatusIndex = [...]uint8{0, 7, 15}

func (i Status) String() string {
	i -= 1
	if i < 0 || i >= Status(len(_StatusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i+1)
	}
	return _StatusName[_StatusIndex[i]:_StatusIndex[i+1]]
}

var _StatusValues = []Status{1, 2}

var _StatusNameToValueMap = map[string]Status{
	_StatusName[0:7]:  1,
	_StatusName[7:15]: 2,
}

// StatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

// StatusValues returns all values of the enum
func StatusValues() []Status {
	return _StatusValues
}

// IsAStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Status) IsAStatus() bool {
	for _, v := range _StatusValues {
		if i == v {
			return true
		}
	}
	return false
}
