# This is the Granted configuration file. This file is the declarative specification for your
# team's access to your cloud environments. As you add more roles and accounts this file will
# grow in size; we recommend splitting it up when it grows large: https://granted.dev/cli/multi-file-config
#
# We recommend checking this config file into version control.
type: granted/v1alpha1

# Admins can update Granted config and approve and audit access requests.
admins:
  - a@commonfate.io
  - b@commonfate.io

# # Roles are permissions in a set of accounts available for users to assume.
roles:
  # lower privilege roles may be granted without requiring reasons or approvals using the "allow" policy on the rule for a group
  - id: s3readonly
    group: Granted_WebApp_Dev_Read

    rules:
      - policy: allow
        group: developers
